const practiceTrials = {
  noTime: [
    {
      scene: {
        prac_stimulus_idx: 5,
        x_ball: 441,
        y_1: 414,
        y_2: 302,
        fallingObjRegion: "right",
        trajectoryChange: "left",
        newTrajChange: "right",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 5,
        choice: "close gt",
        x: 436,
        y: 264,
      },
      timeConstraint: "NA",
    },
    {
      scene: {
        prac_stimulus_idx: 3,
        x_ball: 660,
        y_1: 666,
        y_2: 350,
        fallingObjRegion: "mid-right",
        trajectoryChange: "left",
        newTrajChange: "left",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 3,
        choice: "wrong direction",
        x: 636,
        y: 271,
      },
      timeConstraint: "NA",
    },
    {
      scene: {
        prac_stimulus_idx: 1,
        x_ball: 416,
        y_1: 464,
        y_2: 296,
        fallingObjRegion: "left",
        trajectoryChange: "left",
        newTrajChange: "left",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 1,
        choice: "gt",
        x: 464,
        y: 296,
      },
      timeConstraint: "NA",
    },
  ],
  timed3000: [
    {
      scene: {
        prac_stimulus_idx: 4,
        x_ball: 660,
        y_1: 610,
        y_2: 263,
        fallingObjRegion: "mid-right",
        trajectoryChange: "right",
        newTrajChange: "right",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 4,
        choice: "gt",
        x: 610,
        y: 263,
      },
      timeConstraint: 3000,
    },
    {
      scene: {
        prac_stimulus_idx: 1,
        x_ball: 584,
        y_1: 536,
        y_2: 296,
        fallingObjRegion: "left",
        trajectoryChange: "left",
        newTrajChange: "right",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 1,
        choice: "close gt",
        x: 518,
        y: 312,
      },
      timeConstraint: 3000,
    },
    {
      scene: {
        prac_stimulus_idx: 1,
        x_ball: 416,
        y_1: 464,
        y_2: 296,
        fallingObjRegion: "left",
        trajectoryChange: "left",
        newTrajChange: "left",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 1,
        choice: "far gt",
        x: 437,     // change from 527 to 437 (where valid collision could happen)
        y: 365,     // since far gt, therefore larger change in y too
      },
      timeConstraint: 3000,
    },
  ],
  timed1000: [
    {
      scene: {
        prac_stimulus_idx: 6,
        x_ball: 441,
        y_1: 500,
        y_2: 317,
        fallingObjRegion: "right",
        trajectoryChange: "right",
        newTrajChange: "left",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 6,
        choice: "gt",
        x: 500,
        y: 317,
      },
      timeConstraint: 1000,
    },
    {
      scene: {
        prac_stimulus_idx: 3,
        x_ball: 340,
        y_1: 334,
        y_2: 350,
        fallingObjRegion: "mid-right",
        trajectoryChange: "left",
        newTrajChange: "right",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 3,
        choice: "close gt",
        x: 311,
        y: 328,
      },
      timeConstraint: 1000,
    },
    {
      scene: {
        prac_stimulus_idx: 4,
        x_ball: 660,
        y_1: 610,
        y_2: 263,
        fallingObjRegion: "mid-right",
        trajectoryChange: "right",
        newTrajChange: "right",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 4,
        choice: "far gt",
        x: 645, // change from 525 to 650 (where valid collision could happen)
        y: 359,
      },
      timeConstraint: 1000,
    },
  ],
  timed1000Test: [
    {
      scene: {
        prac_stimulus_idx: 5,
        x_ball: 559,
        y_1: 586,
        y_2: 302,
        fallingObjRegion: "right",
        trajectoryChange: "left",
        newTrajChange: "left",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 5,
        choice: "gt",
        x: 586,
        y: 302,
      },
      timeConstraint: 1000,
    },
    {
      scene: {
        prac_stimulus_idx: 6,
        x_ball: 441,
        y_1: 500,
        y_2: 317,
        fallingObjRegion: "right",
        trajectoryChange: "right",
        newTrajChange: "left",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 6,
        choice: "close gt",
        x: 478, // change from 520 to 478 (where valid collision could happen)
        y: 287,
      },
      timeConstraint: 1000,
    },
    {
      scene: {
        prac_stimulus_idx: 4,
        x_ball: 340,
        y_1: 390,
        y_2: 263,
        fallingObjRegion: "mid-right",
        trajectoryChange: "right",
        newTrajChange: "left",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 4,
        choice: "far gt",
        x: 355, // change from 475 to 350 (where valid collision could happen)
        y: 359, 
      },
      timeConstraint: 1000,
    },
  ],
  timed3000Test: [
    {
      scene: {
        prac_stimulus_idx: 2,
        x_ball: 416,
        y_1: 365,
        y_2: 249,
        fallingObjRegion: "left",
        trajectoryChange: "right",
        newTrajChange: "right",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 2,
        choice: "gt",
        x: 365,
        y: 249,
      },
      timeConstraint: 3000,
    },
    {
      scene: {
        prac_stimulus_idx: 4,
        x_ball: 340,
        y_1: 390,
        y_2: 263,
        fallingObjRegion: "mid-right",
        trajectoryChange: "right",
        newTrajChange: "left",
        flipped: true,
      },
      choice: {
        prac_stimulus_idx: 4,
        choice: "close gt",
        x: 371,
        y: 244,
      },
      timeConstraint: 3000,
    },
    {
      scene: {
        prac_stimulus_idx: 5,
        x_ball: 559,
        y_1: 586,
        y_2: 302,
        fallingObjRegion: "right",
        trajectoryChange: "left",
        newTrajChange: "left",
        flipped: false,
      },
      choice: {
        prac_stimulus_idx: 5,
        choice: "far gt",
        x: 574,
        y: 205,
      },
      timeConstraint: 3000,
    },
  ],
};
